sudo: required
services:
  - docker

before_install:
  - docker build -t busfahrer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run busfahrer/react-test npm run test -- --coverage

after_success:
  - docker build -t busfahrer/multi-worker ./worker
  - docker build -t busfahrer/multi-client ./client
  - docker build -t busfahrer/multi-server ./server
  - docker build -t busfahrer/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push busfahrer/multi-worker
  - docker push busfahrer/multi-client
  - docker push busfahrer/multi-server
  - docker push busfahrer/multi-nginx 

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-361415041242
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
