version: '3'
services:
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 80:80
  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres_password
    image: postgres:latest
  redis:
    image: redis:latest
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
  api:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    build:
      dockerfile: Dockerfile.dev
      context: ./server
